// Lensfun-based lens correction. Lazily loads the bundled Sony E-mount profile
// database (public/lensfun/sony-e.json, generated by scripts/build-lensfun.mjs),
// matches the shot's lens by EXIF name, and builds the same 16-knot
// EmbeddedLensFactors the GPU pipeline already consumes — so Lensfun and Sony
// in-camera corrections share one shader path.
//
// Lensfun models (from include/lensfun/lensfun.h, radius r normalized to half
// the frame's shorter side):
//   distortion ptlens: rd = ru·(a·ru³ + b·ru² + c·ru + 1-a-b-c)
//   distortion poly3:  rd = ru·(1 - k1 + k1·ru²)
//   distortion poly5:  rd = ru·(1 + k1·ru² + k2·ru⁴)
//   tca poly3:         rd_R = ru·(br·ru² + cr·ru + vr)  (and B with bb,cb,vb)
//   vignetting pa:     Cd = Cs / (1 + k1·r² + k2·r⁴ + k3·r⁶)  → gain = 1/poly

import type { EmbeddedLensFactors, ImageMeta } from "@/lib/types";

interface LfDistortion {
  f: number;
  m: string;
  a?: number;
  b?: number;
  c?: number;
  k1?: number;
  k2?: number;
}
interface LfTca {
  f: number;
  vr: number;
  br: number;
  cr: number;
  vb: number;
  bb: number;
  cb: number;
}
interface LfVign {
  f: number;
  av: number;
  k1: number;
  k2: number;
  k3: number;
}
interface LfLens {
  maker: string;
  model: string;
  crop: number;
  distortion: LfDistortion[];
  tca: LfTca[];
  vign: LfVign[];
}

const NC = 16;

let dbPromise: Promise<LfLens[]> | null = null;

function loadDb(): Promise<LfLens[]> {
  if (!dbPromise) {
    dbPromise = fetch("/lensfun/sony-e.json")
      .then((r) => (r.ok ? (r.json() as Promise<LfLens[]>) : []))
      .catch(() => []);
  }
  return dbPromise;
}

function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/f\//g, "f")
    .replace(/[|]/g, " ")
    .replace(/[^a-z0-9.\- ]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tokenize(s: string): string[] {
  return normalize(s).split(" ").filter(Boolean);
}

function numericTokens(tokens: string[]): string[] {
  return tokens.filter((t) => /^\d/.test(t));
}

/** Token-overlap score, requiring the query's numeric tokens (focal/aperture). */
function score(queryTokens: string[], candTokens: string[]): number {
  if (queryTokens.length === 0) return 0;
  const candSet = new Set(candTokens);
  let inter = 0;
  for (const t of queryTokens) if (candSet.has(t)) inter++;
  let s = inter / queryTokens.length;
  for (const n of numericTokens(queryTokens)) {
    if (!candSet.has(n)) s *= 0.25; // focal/aperture mismatch → strong penalty
  }
  return s;
}

function findLens(db: LfLens[], meta: ImageMeta): LfLens | null {
  const lensName = meta.lens?.trim();
  if (!lensName) return null;
  const queryWithMaker = tokenize(`${meta.make} ${lensName}`);
  const query = tokenize(lensName);

  let best: LfLens | null = null;
  let bestScore = 0;
  for (const lens of db) {
    const candTokens = tokenize(`${lens.maker} ${lens.model}`);
    const s = Math.max(score(query, candTokens), score(queryWithMaker, candTokens));
    if (s > bestScore) {
      bestScore = s;
      best = lens;
    }
  }
  return bestScore >= 0.6 ? best : null;
}

function nearestByFocal<T extends { f: number }>(entries: T[], focal: number): T | null {
  if (entries.length === 0) return null;
  let best = entries[0];
  let bestDist = Math.abs(entries[0].f - focal);
  for (const e of entries) {
    const d = Math.abs(e.f - focal);
    if (d < bestDist) {
      bestDist = d;
      best = e;
    }
  }
  return best;
}

function distortionFactor(d: LfDistortion, ru: number): number {
  if (d.m === "ptlens") {
    const a = d.a ?? 0;
    const b = d.b ?? 0;
    const c = d.c ?? 0;
    return a * ru ** 3 + b * ru ** 2 + c * ru + (1 - a - b - c);
  }
  if (d.m === "poly5") {
    const k1 = d.k1 ?? 0;
    const k2 = d.k2 ?? 0;
    return 1 + k1 * ru ** 2 + k2 * ru ** 4;
  }
  // poly3 (and fallback)
  const k1 = d.k1 ?? 0;
  return 1 - k1 + k1 * ru ** 2;
}

/** Build 16-knot correction factors for a matched lens at the shot's settings. */
function buildFactors(lens: LfLens, meta: ImageMeta, width: number, height: number): EmbeddedLensFactors {
  const focal = meta.focalLength || 0;
  const aperture = meta.aperture || 0;
  const aspect = Math.max(width, height) / Math.min(width, height);
  const cornerR = Math.hypot(aspect, 1); // Lensfun radius at the frame corner

  const dist = nearestByFocal(lens.distortion, focal);
  const tca = nearestByFocal(lens.tca, focal);
  // Vignetting: nearest focal, then nearest aperture within that focal.
  const vignFocal = nearestByFocal(lens.vign, focal);
  let vign: LfVign | null = null;
  if (vignFocal) {
    const sameFocal = lens.vign.filter((v) => v.f === vignFocal.f);
    vign = sameFocal.reduce((best, v) =>
      Math.abs(v.av - aperture) < Math.abs(best.av - aperture) ? v : best,
    );
  }

  const distFactor = new Float32Array(NC);
  const caRFactor = new Float32Array(NC);
  const caBFactor = new Float32Array(NC);
  const vigGain = new Float32Array(NC);

  for (let i = 0; i < NC; i++) {
    const ru = (i / (NC - 1)) * cornerR;
    distFactor[i] = dist ? distortionFactor(dist, ru) : 1;
    caRFactor[i] = tca ? tca.vr + tca.cr * ru + tca.br * ru ** 2 : 1;
    caBFactor[i] = tca ? tca.vb + tca.cb * ru + tca.bb * ru ** 2 : 1;
    if (vign) {
      const poly = 1 + vign.k1 * ru ** 2 + vign.k2 * ru ** 4 + vign.k3 * ru ** 6;
      vigGain[i] = poly > 0 ? 1 / poly : 1;
    } else {
      vigGain[i] = 1;
    }
  }

  const cornerFactor = distFactor[NC - 1];
  const scale = cornerFactor > 0 ? 1 / cornerFactor : 1;
  return { nc: NC, distFactor, caRFactor, caBFactor, vigGain, scale };
}

export interface LensfunMatch {
  factors: EmbeddedLensFactors;
  name: string;
}

/** Match the image's lens in the Lensfun DB and build correction factors. */
export async function matchLensfun(
  meta: ImageMeta,
  width: number,
  height: number,
): Promise<LensfunMatch | null> {
  const db = await loadDb();
  const lens = findLens(db, meta);
  if (!lens) return null;
  return { factors: buildFactors(lens, meta, width, height), name: `${lens.maker} ${lens.model}` };
}
